service: aws-runtime-pypy

provider:
  name: aws
  runtime: provided.al2 #python3.7
  region: us-east-1

package:
  patterns:
    - test/**
    - pypy3.9-v7.3.15-linux64/bin/*debug
    #- pypy3-v6.0.0-linux64/lib-python/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: primes
          method: get
